image:
  file: .gitpod.Dockerfile

tasks:
  - name: Run Spring Boot
    init: mvn clean install -DskipTests
    command: mvn spring-boot:run

ports:
  - port: 8080
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - pivotal.vscode-spring-boot
    - redhat.java
    - vscjava.vscode-maven